# Generated by Django 5.2.6 on 2025-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "캘린더 이벤트",
                "verbose_name_plural": "캘린더 이벤트 목록",
                "db_table": "calendar_event",
            },
        ),
    ]
