# Generated by Django 4.2.24 on 2025-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '캘린더 이벤트',
                'verbose_name_plural': '캘린더 이벤트 목록',
                'db_table': 'calendar_event',
            },
        ),
        migrations.CreateModel(
            name='CommunityBoard',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=100, verbose_name='게시판 제목')),
                ('board_type', models.CharField(max_length=20, verbose_name='게시판 유형')),
            ],
            options={
                'verbose_name': '커뮤니티 게시판',
                'verbose_name_plural': '커뮤니티 게시판 목록',
                'db_table': 'community_board',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글 목록',
                'db_table': 'community_comment',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('open', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('view', models.IntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글 목록',
                'db_table': 'community_post',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=30, verbose_name='알림 유형')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'db_table': 'notification',
            },
        ),
    ]
