# Generated by Django 5.2.6 on 2025-11-13 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityBoard",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "board_title",
                    models.CharField(max_length=100, verbose_name="게시판 제목"),
                ),
                (
                    "board_type",
                    models.CharField(max_length=20, verbose_name="게시판 유형"),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시판",
                "verbose_name_plural": "커뮤니티 게시판 목록",
                "db_table": "community_board",
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.class",
                        verbose_name="강의",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "캘린더 이벤트",
                "verbose_name_plural": "캘린더 이벤트 목록",
                "db_table": "calendar_event",
            },
        ),
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("open", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("view", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.communityboard",
                        verbose_name="게시판",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시글",
                "verbose_name_plural": "커뮤니티 게시글 목록",
                "db_table": "community_post",
            },
        ),
        migrations.CreateModel(
            name="CommunityComment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_content", models.TextField(verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.communitypost",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 댓글",
                "verbose_name_plural": "커뮤니티 댓글 목록",
                "db_table": "community_comment",
            },
        ),
        migrations.CreateModel(
            name="MeetingRequest",
            fields=[
                ("meeting_id", models.AutoField(primary_key=True, serialize=False)),
                ("meeting_time", models.DateTimeField(verbose_name="상담 요청 시간")),
                ("message", models.TextField(verbose_name="메시지 내용")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.messengerchannel",
                        verbose_name="일정 조율 채널",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"role": "instructor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="강사",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "상담 요청",
                "verbose_name_plural": "상담 요청 목록",
                "db_table": "meeting_request",
            },
        ),
        migrations.CreateModel(
            name="RequestClass",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(max_length=10, verbose_name="요청 유형"),
                ),
                (
                    "requested_start_time",
                    models.DateTimeField(verbose_name="요청 시작 시간"),
                ),
                (
                    "requested_end_time",
                    models.DateTimeField(verbose_name="요청 종료 시간"),
                ),
                (
                    "approved",
                    models.CharField(
                        choices=[("승인", "승인"), ("거절", "거절"), ("보류", "보류")],
                        default="보류",
                        max_length=20,
                        verbose_name="승인 상태",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="수신 확인"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.class",
                        verbose_name="요청 대상 강의",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인 매니저",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "강의 신청/수정 요청",
                "verbose_name_plural": "강의 신청/수정 요청 목록",
                "db_table": "request_class",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(max_length=30, verbose_name="알림 유형"),
                ),
                ("message", models.TextField(verbose_name="메시지")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "class_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.classcomment",
                        verbose_name="강의 댓글 참조",
                    ),
                ),
                (
                    "community_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.communitycomment",
                        verbose_name="커뮤니티 댓글 참조",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.calendarevent",
                        verbose_name="이벤트 참조",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.meetingrequest",
                        verbose_name="상담 요청 참조",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신 사용자",
                    ),
                ),
                (
                    "class_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.requestclass",
                        verbose_name="강의 요청 참조",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림 목록",
                "db_table": "notification",
            },
        ),
    ]
