# Generated by Django 5.2.6 on 2025-11-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="requestclass",
            name="class_obj",
        ),
        migrations.RemoveField(
            model_name="requestclass",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="requestclass",
            name="requester",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="class_request",
        ),
        migrations.DeleteModel(
            name="MeetingRequest",
        ),
        migrations.DeleteModel(
            name="RequestClass",
        ),
    ]
