# Generated by Django 4.2.24 on 2025-11-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='class_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.classcomment', verbose_name='강의 댓글 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='community_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.communitycomment', verbose_name='커뮤니티 댓글 참조'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calendarevent', verbose_name='이벤트 참조'),
        ),
    ]
