# Generated by Django 5.2.6 on 2025-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_images/",
                        verbose_name="강의 썸네일",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "프로그래밍"),
                            ("design", "디자인"),
                            ("business", "비즈니스"),
                            ("language", "외국어"),
                            ("general", "일반"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                            (6, "일요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                ("start_date", models.DateField(verbose_name="강의 시작일")),
                ("end_date", models.DateField(verbose_name="강의 종료일")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "course",
                "ordering": ["-created_at"],
            },
        ),
    ]
