# Generated by Django 4.2.24 on 2025-11-24 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='강의명')),
                ('description', models.TextField(verbose_name='강의 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의 목록',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
    ]
