# Generated by Django 5.2.6 on 2025-12-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("Digital", "디지털"),
                    ("AI", "AI"),
                    ("Making", "메이킹"),
                    ("Computing", "컴퓨팅"),
                    ("general", "일반"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
