# Generated by Django 5.2.6 on 2025-11-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(
                blank=True, default="2000-01-01", verbose_name="생년월일"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="010-0000-0000",
                max_length=15,
                unique=True,
                verbose_name="전화번호",
            ),
        ),
    ]
