# Generated by Django 4.2.24 on 2025-11-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
