# Generated by Django 4.2.24 on 2025-11-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '채널 멤버',
                'verbose_name_plural': '채널 멤버 목록',
                'db_table': 'channel_member',
            },
        ),
        migrations.CreateModel(
            name='MessengerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, verbose_name='채널명')),
                ('channel_type', models.CharField(max_length=20, verbose_name='채널 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '메신저 채널',
                'verbose_name_plural': '메신저 채널 목록',
                'db_table': 'messenger_channel',
            },
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='전송 일시')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messengerchannel', verbose_name='채널')),
            ],
            options={
                'verbose_name': '메신저 메시지',
                'verbose_name_plural': '메신저 메시지 목록',
                'db_table': 'messenger_messages',
            },
        ),
    ]
