# Generated by Django 5.2.6 on 2025-12-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="channelmember",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.messengerchannel",
                verbose_name="채널",
            ),
        ),
        migrations.AddField(
            model_name="messengermessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.messengerchannel",
                verbose_name="채널",
            ),
        ),
        migrations.AddField(
            model_name="messengermessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="보낸 사람",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelmember",
            unique_together={("channel", "user")},
        ),
    ]
