# Generated by Django 5.2.6 on 2025-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField()),
                ("max_score", models.IntegerField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignment_files/%Y/%m/%d/",
                        verbose_name="첨부 파일(PDF 등)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assignment",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseNotice",
            fields=[
                ("notice_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="상단 고정"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_notice",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseQuestion",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="해결됨"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_question",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("progress", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enrollment",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="답변 내용")),
                (
                    "is_instructor_answer",
                    models.BooleanField(default=False, verbose_name="강사 답변"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "question_answer",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="submissions/%Y/%m/%d/",
                        verbose_name="제출 파일",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="텍스트 답변")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "submission",
            },
        ),
        migrations.CreateModel(
            name="WeeklyContent",
            fields=[
                ("content_id", models.AutoField(primary_key=True, serialize=False)),
                ("week_number", models.IntegerField(verbose_name="주차")),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course_materials/",
                        verbose_name="자료 파일",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="동영상 URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "weekly_content",
                "ordering": ["week_number"],
            },
        ),
    ]
