# Generated by Django 4.2.24 on 2025-12-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(verbose_name='주차')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='자료 파일')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='동영상 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_contents', to='course.course')),
            ],
            options={
                'db_table': 'weekly_content',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseNotice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notices', to='course.course')),
            ],
            options={
                'db_table': 'course_notice',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
