# Generated by Django 4.2.24 on 2025-12-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_initial'),
        ('classroom', '0003_weeklycontent_coursenotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결됨')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.course')),
            ],
            options={
                'db_table': 'course_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('is_instructor_answer', models.BooleanField(default=False, verbose_name='강사 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.coursequestion')),
            ],
            options={
                'db_table': 'question_answer',
                'ordering': ['created_at'],
            },
        ),
    ]
