# Generated by Django 4.2.24 on 2025-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_coursequestion_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='피드백'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='점수'),
        ),
    ]
