# Generated by Django 4.2.24 on 2025-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_submission_options_assignment_resource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/%Y/%m/%d/', verbose_name='첨부 파일(PDF 등)'),
        ),
    ]
