# Generated by Django 4.2.24 on 2025-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_assignment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='resource_url',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
