# Generated by Django 4.2.24 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimc',
            name='pdf_path',
            field=models.FileField(upload_to='dimc_reports/'),
        ),
    ]
