# Generated by Django 5.2.6 on 2025-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityBoard",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "board_title",
                    models.CharField(max_length=100, verbose_name="게시판 제목"),
                ),
                (
                    "board_type",
                    models.CharField(max_length=20, verbose_name="게시판 유형"),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시판",
                "verbose_name_plural": "커뮤니티 게시판 목록",
                "db_table": "community_board",
            },
        ),
        migrations.CreateModel(
            name="CommunityComment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_content", models.TextField(verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 댓글",
                "verbose_name_plural": "커뮤니티 댓글 목록",
                "db_table": "community_comment",
            },
        ),
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("open", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("view", models.IntegerField(default=0, verbose_name="조회수")),
            ],
            options={
                "verbose_name": "커뮤니티 게시글",
                "verbose_name_plural": "커뮤니티 게시글 목록",
                "db_table": "community_post",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("notice_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="상단 고정"),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항 목록",
                "db_table": "notice",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
