# Generated by Django 5.2.6 on 2025-12-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityboard",
            name="board_type",
            field=models.CharField(max_length=21, verbose_name="게시판 유형"),
        ),
    ]
