# Generated by Django 5.2.6 on 2025-12-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_communityboard_board_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitycomment",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
    ]
