# Generated by Django 5.2.6 on 2025-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_communitycomment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[("NOTICE", "공지"), ("MAINT", "점검")],
                default="NOTICE",
                max_length=10,
                verbose_name="유형",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="target",
            field=models.CharField(
                choices=[("ALL", "전체"), ("STUDENT", "학생"), ("TEACHER", "강사")],
                default="ALL",
                max_length=10,
                verbose_name="대상",
            ),
        ),
        migrations.AlterField(
            model_name="communitycomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
    ]
